# Generated by Django 4.2.13 on 2024-05-18 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="media"
            ),
            preserve_default=False,
        ),
    ]
